### ISSUE TITLE
Renovate can do that's all

### ISSUE THREAD

**Issue by MaxymVlasov** [suzuki-shunsuke/pinact#117]
Very interesting solution, but Renovate is able to pin the exact version of dependency. 

Checkout this PR: https://github.com/antonbabenko/pre-commit-terraform/pull/464

So, I suppose you find a Renovate bug - please create a discussion for that in https://github.com/renovatebot/renovate/discussions

or, the reason why this solution was created, was a lack of RTFM (who read these docs, right? :) and checking how Renovate org uses Renovate itself.
 > ![image](https://github.com/suzuki-shunsuke/pinact/assets/11096782/28ce357b-70d8-4ad8-9731-269f4332abcf)
 
 
 Btw, you can just start using https://github.com/SpotOnInc/renovate-config/ and forget about this and, many other problems.

**Comment by MaxymVlasov** [comment]
I am not sure what exactly enables Renovate to do `vX -> vX.Y.Z` updates, but if it can't be done by enabling-disabling configuration, then it was done on 1 Feb 2021 by this solution:

https://github.com/renovatebot/.github/blame/f5a5fc056c78fe7741a4fde59ee94feed622cd3e/default.json#L46-L50

**Comment by suzuki-shunsuke** [comment]
Thank you for pointing it out.
I think this discussion is related.

- https://github.com/renovatebot/renovate/discussions/21901
- https://github.com/suzuki-shunsuke/test-renovate-2/blob/f44f0ebb0db4b478ce4bedb11ade3d41a66bdeae/renovate.json5#L9-L15

The preset `SpotOnInc/renovate-config` includes the setting.

https://github.com/SpotOnInc/renovate-config/blob/5e861bec9b13bd84575122dd7427ffeb4646d1be/default.json#L45-L50

**Comment by MaxymVlasov** [comment]
Aha, so maintainers have plans to resolve it in a more user-friendly way than just adding this kind of hack to docs, nice.

>The preset SpotOnInc/renovate-config includes the setting.

Yep, I just pointed to the original. I included it from day 1, so until I was pointed to `pinact` I didn't know that this problem exist.

Do you plan to maintain this tool until https://github.com/renovatebot/renovate/discussions/21901 resolution or archive `pinact` specifying that there is a Renovate-native ~hack~ solution for that? Just curious.

**Comment by suzuki-shunsuke** [comment]
> Do you plan to maintain this tool until https://github.com/renovatebot/renovate/discussions/21901 resolution or archive pinact specifying that there is a Renovate-native hack solution for that? Just curious.

I don't decide yet. I don't have any plan to add new features to pinact for now,
so maybe I'll archive this repository.
Maybe pinact is still useful for non Renovate users, but I'm not sure.

**Comment by korenyoni** [comment]
This issue seems to conflate the [pinact CLI](https://github.com/suzuki-shunsuke/pinact) and its [GHA counterpart](https://github.com/suzuki-shunsuke/pinact-action).

Even if renovatebot can be used instead of https://github.com/suzuki-shunsuke/pinact-action, `pinact` itself (this repo) can be run locally and is useful for initially migrating GHA version references from tags to their digest counterparts without having to deal with any PRs.

Another great use case for pinact (again, the CLI itself, not the GHA), is to include it in pre-commit hooks.

**Comment by MaxymVlasov** [comment]
>Another great use case for pinact (again, the CLI itself, not the GHA), is to include it in pre-commit hooks.

Great idea, but any networking operations are time-consuming, that's why many users, including myself, prefer to move such kinds of checks (and fix push) inside PR, than do it locally on each commit when action changes. And, from my practice, you still need to [run `pre-commit` checks in PRs](https://github.com/antonbabenko/pre-commit-terraform/blob/789973b35ac06387395010a013ea7719a279bfd0/.github/workflows/pre-commit.yaml), because many contributors too lazy to read docs and install all the needed stuff

**Comment by ledmonster** [comment]
Should I use pinact instead of [helpers:pinGitHubActionDigestsToSemver](https://docs.renovatebot.com/presets-helpers/#helperspingithubactiondigeststosemver)? What is the advantage of pinact now?

**Comment by suzuki-shunsuke** [comment]
There are some advantages of pinact.

1. pinact is useful when we send pull requests to add actions.
In this case, we can't pin actions by Renovate before merging pull requests.
If we use linters such as [ghalint](https://github.com/suzuki-shunsuke/ghalint) in CI, we need to pin actions before merging pull requests.

https://github.com/suzuki-shunsuke/ghalint/blob/main/docs/policies/008.md

2. pinact is useful to update actions manually for some reasons.
When we use Renovate actions are updated by Renovate so we don't need to update actions manually, but sometimes we want to update actions manually.
In this case, pinact is useful to pin actions.
3. pinact is useful for users not using Renovate.
4. [pinact supports verifying version annotations](https://github.com/suzuki-shunsuke/pinact/blob/main/docs/codes/001.md)

**Comment by suzuki-shunsuke** [comment]
I've updated the document.

- https://github.com/suzuki-shunsuke/pinact/pull/599

I close this issue as it has served its purpose.

**Comment by ledmonster** [comment]
@suzuki-shunsuke thank you. probably we should remove this line in README now.

> [Renovate's helpers:pinGitHubActionDigests](https://docs.renovatebot.com/presets-helpers/#helperspingithubactiondigests) pins GitHub Actions versions by commit hash, but this doesn't change the short format tag such as v2 to the long format tag such as v2.0.0.

**Comment by suzuki-shunsuke** [comment]
I don't think so.

- https://github.com/suzuki-shunsuke/test-renovate/pull/294
- https://github.com/suzuki-shunsuke/test-renovate/blob/097797150235f0455e3b99db52253a02c2994f22/renovate.json5#L4

**Comment by suzuki-shunsuke** [comment]
Do you mean we should remove the line because [helpers:pinGitHubActionDigestsToSemver](https://docs.renovatebot.com/presets-helpers/#helperspingithubactiondigeststosemver) is better than [helpers:pinGitHubActionDigests](https://docs.renovatebot.com/presets-helpers/#helperspingithubactiondigests)?
Even if so, I don't think we need to remove the line.

**Comment by suzuki-shunsuke** [comment]
Oh, I see. Sorry, probably I misunderstood.

I thought you talked about https://github.com/suzuki-shunsuke/pinact/blob/91c6a42d60419bd877174a1ab6a989c77fc04ca2/README.md?plain=1#L325 , but probably you talked about https://github.com/suzuki-shunsuke/pinact/blob/91c6a42d60419bd877174a1ab6a989c77fc04ca2/README.md?plain=1#L66 .
Indeed, https://github.com/suzuki-shunsuke/pinact/blob/91c6a42d60419bd877174a1ab6a989c77fc04ca2/README.md?plain=1#L66 should be modified.
I'll consider it.

**Comment by suzuki-shunsuke** [comment]
I'll update the document. Thank you for pointing it out.

- https://github.com/suzuki-shunsuke/pinact/pull/602

**Comment by ledmonster** [comment]
Thank you!!

2024年11月15日(金) 20:17 Shunsuke Suzuki ***@***.***>:
